version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - "sistema-sensor-network"
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - "postgres"
      - "rabbitmq"
      - "external-app"
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - "sistema-sensor-network"
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - "15672"
      - "5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  postgres:
    image: postgres:latest
    networks:
      - "sistema-sensor-network"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  external-app:
    build:
      context: ./external_app
      dockerfile: Dockerfile
    networks:
      - "sistema-sensor-network"
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
    - EXTERNAL_APP_PORT=5000
networks:
  sistema-sensor-network:
    driver: bridge