version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - "sistema-sensor-network"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    expose:
      - "${BACKEND_PORT}"
    depends_on:
      - "db"
      - "rabbitmq"
      - "external_app"
    environment: # Environment variables override application.properties
        SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
        SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
        SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
        SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
        SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
        SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
        EXTERNAL_APP_PROTOCOL: ${EXTERNAL_APP_PROTOCOL}
        EXTERNAL_APP_HOST: ${EXTERNAL_APP_HOST}
        EXTERNAL_APP_PORT: ${EXTERNAL_APP_PORT}
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - "sistema-sensor-network"
    ports:
      - "${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}"
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
    expose:
      - "${RABBITMQ_MANAGEMENT_PORT}"
      - "${RABBITMQ_PORT}"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
  db:
    image: postgres:latest
    restart: always
    networks:
      - "sistema-sensor-network"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  external_app:
    build:
      context: ./external_app
      dockerfile: Dockerfile
    networks:
      - "sistema-sensor-network"
    ports:
      - "${EXTERNAL_APP_PORT}:${EXTERNAL_APP_PORT}"
    expose:
      - "${EXTERNAL_APP_PORT}"
    environment:
      - EXTERNAL_APP_PORT=${EXTERNAL_APP_PORT}
networks:
  sistema-sensor-network:
    driver: bridge